# Generated by Django 3.2.3 on 2021-07-02 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0003_alter_entry_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics', to='auth.user'),
            preserve_default=False,
        ),
    ]
